language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
env:
  - NOCOV=true
  - NOCOV=true PA_ORM=mongoid
  - NOCOV=true PA_ORM=mongoid PA_PURGE=true
  - NOCOV=true PA_ORM=mongo_mapper
services:
  - mongodb
matrix:
  exclude:
    - rvm: 1.9.2
      env: "NOCOV=true PA_ORM=mongoid"
    - rvm: 1.9.2
      env: "NOCOV=true PA_ORM=mongoid PA_PURGE=true"
email:
  recipients:
    - piotrek@okonski.org
    - jakub@okonski.org
  on_success: change
  on_failure: always
